### ISSUE TITLE
java.security.KeyStoreException: Uninitialized keystore when retrieving a SensitiveItem

### ISSUE THREAD

**Issue by enmolenici** [telekom/SmartCredentials-SDK-android#12]
KeyStoreException thrown when retrieving a SensitiveItem. The issue happens only on Android 9, mostly on Samsung devices. 

**Expected result**
The SensitiveItem is successfully retrieved
**Actual result**
KeyStoreException is thrown
**Severity&Priority**
Major - 4
**Environment**
Android 9 

Obfuscated stacktrace:
`
| 0 | f.b.b.d.e.a: Could not decrypt text.f.b.b.k.c.a: java.security.KeyStoreException: Uninitialized keystore
-- | --
! | 1 | at f.b.b.k.b.c.b(Unknown Source:103)
  | 2 | at f.b.b.k.b.b.b(Unknown Source:2)
  | 3 | at f.b.b.l.b.b(Unknown Source:2)
  | 4 | at f.b.b.d.a.a.b(Unknown Source:9)
  | 5 | at f.b.b.b.h.a(Unknown Source:3)
`

**Comment by en-agraur** [comment]
Hi! After taking a look over the issue, it would happen if the keystore is not initialized correctly before doing an operation with it. I will have to go deeper with the investigation, since it can't reproduce it for the moment and will have to see why it's only happening in some cases. Will be back with a resolution as soon as possible. Any more information regarding this is appreciated.

**Comment by en-agraur** [comment]
Hi again! We were not able to reproduce the issue, but we came with a possible fix. It is already available in the version 5.14.21 of the library. Let us know if this lowers the number of crashes, in order to know if we continue investigating or close this issue. Thank you!

**Comment by enmolenici** [comment]
Thank you! We will give it a try and let you know.
